
const ProductsList = [
  {name: 'Топор', price: 300, unit_id: 1},
  {name: 'Калун', price: 550, unit_id: 1},
  {name: 'Цепь 5', price: 50, unit_id: 2},
  {name: 'Трос 5', price: 20, unit_id: 2},
  {name: 'Трос 8', price: 30, unit_id: 2},
  {name: 'Першня', price: 220, unit_id: 1},
  {name: 'Пила', price: 250, unit_id: 1},
  {name: 'Технический спирт', price: 99, unit_id: 6},
  {name: 'Дестилированная вода', price: 49, unit_id: 6},
  {name: 'Болт 5', price: 5.5, unit_id: 1},
  {name: 'Гвозди 10', price: 180, unit_id: 5},
  {name: 'Коловорот', price: 80, unit_id: 1},
  {name: 'Болт 8', price: 10, unit_id: 1},
  {name: 'Болт 10', price: 15, unit_id: 1},
  {name: 'Саморезы по дереву', price: 2.5, unit_id: 1},
  {name: 'Саморезы по дереву', price: 600, unit_id: 5},
  {name: 'Черенок для лопаты', price: 70, unit_id: 1},
  {name: 'Топорище', price: 90, unit_id: 1},
  {name: 'Топор сучкаруб', price: 330, unit_id: 1},
  {name: 'Кирка', price: 350, unit_id: 1},
  {name: 'Шило', price: 70, unit_id: 1},
  {name: 'Сверло 5', price: 60, unit_id: 1},
  {name: 'Сверло 8', price: 80, unit_id: 1},
  {name: 'Сверло 10', price: 100, unit_id: 1},
  {name: 'Бита', price: 15, unit_id: 1},
  {name: 'Отвертка крестовая', price: 70, unit_id: 1},
  {name: 'Отвертка плоская', price: 70, unit_id: 1},
  {name: 'Отвертка универсальная', price: 120, unit_id: 1},
  {name: 'Молоток', price: 150, unit_id: 1},
  {name: 'Кувалда', price: 450, unit_id: 1},
  {name: 'Лом', price: 550, unit_id: 1},
  {name: 'Струбцина', price: 200, unit_id: 1},
  {name: 'Вертель', price: 30, unit_id: 1},
  {name: 'Задвижка', price: 90, unit_id: 1},
  {name: 'Петли', price: 160, unit_id: 1},
  {name: 'Рубанок', price: 290, unit_id: 1},
  {name: 'Долото', price: 170, unit_id: 1},
  {name: 'Рашпиль', price: 100, unit_id: 1},
  {name: 'Напильник', price: 120, unit_id: 1},
  {name: 'Наждачная бумага', price: 300, unit_id: 2},
  {name: 'Точильный камень', price: 200, unit_id: 1},
  {name: 'Циркулярная пила', price: 300, unit_id: 1},
  {name: 'Плоскогубцы', price: 360, unit_id: 1},
  {name: 'Клещи', price: 390, unit_id: 1},
  {name: 'Пинцет', price: 60, unit_id: 1},
  {name: 'Ножницы', price: 130, unit_id: 1},
  {name: 'Кусачки', price: 210, unit_id: 1},
  {name: 'Ножницы по металу', price: 340, unit_id: 1},
  {name: 'Гаечный ключ 7', price: 90, unit_id: 1},
  {name: 'Гаечный ключ 10', price: 110, unit_id: 1},
  {name: 'Гаечный ключ 12', price: 120, unit_id: 1},
  {name: 'Гаечный ключ 13', price: 120, unit_id: 1},
  {name: 'Гаечный ключ 17', price: 150, unit_id: 1},
  {name: 'Гаечный ключ 20', price: 200, unit_id: 1},
  {name: 'Гвоздодер', price: 320, unit_id: 1},
  {name: 'Стамеска', price: 89, unit_id: 1},
  {name: 'Тиски', price: 700, unit_id: 1},
  {name: 'Буравчик', price: 45, unit_id: 1},
  {name: 'Пила двуручная', price: 600, unit_id: 1},
  {name: 'Лобзик', price: 270, unit_id: 1},
  {name: 'Рулетка', price: 210, unit_id: 1},
  {name: 'Нож', price: 300, unit_id: 1},
  {name: 'Шнур', price: 200, unit_id: 2},
  {name: 'Канат 50', price: 400, unit_id: 2},
  {name: 'Штангенциркуль', price: 200, unit_id: 1},
  {name: 'Уровень', price: 300, unit_id: 1},
  {name: 'Отвес', price: 100, unit_id: 1},
  {name: 'Линейка', price: 150, unit_id: 1},
];

export default {
  ProductsList,
};
